version: '3'
services:

  wordpress:
    container_name: wordpress
    build:
      context: ./config/php
      args:
        - WP_IMAGE=wordpress:${WORDPRESS_VERSION:-php8.2-fpm}
    image: wordpress:${WORDPRESS_VERSION:-php8.2-fpm}
    depends_on:
      - mariadb
      - redis
    environment:
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mariadb}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wpadmin}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
      - WP_ALLOW_MULTISITE='true'
      - WP_SITE_TITLE=${WP_SITE_TITLE:-SiteTitle}
      - WP_ADMIN_USER=${WP_ADMIN_USER:-wpadmin}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD:-wpadminpassword}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL:-you@example.com}
      - WORDPRESS_CONFIG_EXTRA=${WORDPRESS_CONFIG_EXTRA}
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${WORDPRESS_DIR:-./core/wordpress}:/var/www/html
      - ${WORDPRESS_CONTENT_DIR:-./wordpress/wp-content}:/var/www/html/wp-content
    restart: always  
    networks:
      - wordpress-network
      
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ${MYSQL_DIR:-./core/mysql}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-wordpress}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    restart: always
    networks:
      - wordpress-network

  nginx:
    build: 
      context: ./config/nginx
      args:
        - NGINX_IMAGE=nginx:${NGINX_VERSION:-latest}
        - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - '${NGINX_HTTP_PORT:-80}:80'
      - '${NGINX_HTTPS_PORT:-443}:443'
    volumes:
      - ${WORDPRESS_DIR:-./core/wordpress}:/var/www/html
      - ${WORDPRESS_CONTENT_DIR:-./wordpress/wp-content}:/var/www/html/wp-content
      - ${NGINX_LOG_DIR:-./core/logs/nginx}:/var/log/nginx
      - ${CERTS_DIR:-./core/certs}:/etc/letsencrypt
    restart: always
    networks:
      - wordpress-network

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    restart: always
    expose:
      - '6379'
    networks:
      - wordpress-network        

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - wordpress-network
      
volumes:
  mariadb: {}
  wordpress: {}

networks:
  wordpress-network:
    driver: bridge