version: '3.3'

networks:
  wordpress:

services:
  nginx:
    build:
      context: ./config/nginx
      args:
      - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - .env
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html:delegated
    depends_on:
      - php
      - mariadb
    networks:
      - wordpress

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - ${MYSQL_DIR:-./mysql}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password123!}
      - MYSQL_DATABASE=${WP_DB_NAME:-wordpress}
      - MYSQL_USER=${WP_DB_USER:-wpadmin}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD:-password123!}
      - MYSQL_ALLOWED_EMPTY_PASSWORD=${MYSQL_ALLOWED_EMPTY_PASSWORD:-no}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-password123!}
    restart: always
    networks:
      - wordpress
 
  php:
    build:
      context: ./config/php
    container_name: php
    depends_on:
      - mariadb
    volumes:
      - ./html:/var/www/html:delegated
    networks:
      - wordpress

  wp:
    build:
      context: ./config/php
    container_name: wp
    entrypoint: ['wp', '--allow-root']
    volumes:
      - ./html:/var/www/html:delegated
    networks:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - wordpress