version: '3.7'  # Updated for profile support

networks:
  wordpress:

services:

  nginx:
    build:
      context: ./config/nginx
    container_name: "${DOMAIN_NAME}_nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./www/${DOMAIN_NAME}:/var/www/html:delegated"
    depends_on:
      - php
      - mariadb
      - wp
    networks:
      - wordpress
    profiles:
      - "${DOMAIN_NAME}"

  php:
    build:
      context: ./config/php
    container_name: "${DOMAIN_NAME}_php"
    volumes:
      - "./www/${DOMAIN_NAME}:/var/www/html:delegated"  # Adjusted to match your desired path structure
    networks:
      - wordpress
    profiles:
      - "${DOMAIN_NAME}"

  wp:
    build:
      context: ./config/php
    container_name: "${DOMAIN_NAME}_wp"  # Added dynamic naming to avoid conflicts
    entrypoint: ['wp', '--allow-root']
    volumes:
      - "./www/${DOMAIN_NAME}:/var/www/html:delegated"  # Adjusted to match your desired path structure
    networks:
      - wordpress
    profiles:
      - "${DOMAIN_NAME}"
